### ISSUE TITLE
fine here's a checklist

### ISSUE THREAD

**Issue by diazrenata** [diazrenata/invisible-string#3]
- [ ] model outcomes table
- [ ] slopes histogram
- [ ] decoupling 1:1 plot
- [ ] demo figure
- [ ] clean up variability v stasis
- [ ] gams box
- [ ] discussion
- [ ] tidy up intro
- [ ] off-by-one error 30 v 31 years
- [ ] ~update abstract - currently it is in GEB format, and focused on discrete time, and incorrect in the description of results (for continuous time) and focused to heavily on ISDs, and not enough about methodological bats in the attic.~ for a dissertation chapter you don't need an abstract 🙃 
- [ ] formattingggg
